### ISSUE TITLE
lib import erro when run the demo

### ISSUE THREAD

**Issue by c3l2** [HeKun-NVIDIA/py-darknet-yolo#1]
I built the project follow the instruction. I got the following error when I ran the demo: 
Traceback (most recent call last):
  File "run_yfcc_det.py", line 7, in <module>
    import pyDarknet
  File "/mnt/ssd/temp.cs/py-darknet-yolo/pyDarknet/__init__.py", line 1, in <module>
    from detector import Darknet_ObjectDetector as ObjectDetector
  File "/mnt/ssd/temp.cs/py-darknet-yolo/pyDarknet/detector.py", line 1, in <module>
    from libpydarknet import DarknetObjectDetector
ImportError: /mnt/ssd/temp.cs/py-darknet-yolo/pyDarknet/libpydarknet.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE

It seems a libboost version error, but I donn't know how to fix. Can anybody help me?

**Comment by home3k** [comment]
I had the same problem. Waiting to fix.

**Comment by ajbolous** [comment]
i have the same problem...
